import type { Metadata } from "next"
import { Inter } from "next/font/google"
import "./globals.css"
import { i18n, Locale } from "@/i18n.config"
import Header from "@/components/Header"
import Footer from "@/components/Footer"
import Providers from "@/components/Providers"
import { getDictionary } from "../../lib/dictionaries"

const inter = Inter({
	subsets: ["latin"],
	variable: "--font-inter"
})

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app"
}

export async function generateStaticParams() {
	return i18n.locales.map(locale => ({ lang: locale }))
}

export default async function RootLayout({
	children,
	params
}: Readonly<{
	children: React.ReactNode
	params: { lang: Locale }
}>) {
	const { header, footer } = await getDictionary(params.lang)
	return (
		<html lang={params.lang}>
			<body className={inter.className}>
				<Providers>
					<Header header={header} params={params} />
					{children}
					<Footer footer={footer} />
				</Providers>
			</body>
		</html>
	)
}
